fix github pipeline errors

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,32 +41,38 @@ jobs:
 
       - name: Create S3 Bucket and DynamoDB Table for Terraform Backend
         run: |
-          echo "Creating S3 bucket and DynamoDB table for Terraform backend..."
-
-          # Create S3 bucket
-          aws s3api create-bucket --bucket ${{ env.S3_BUCKET_NAME }} --region ${{ env.TF_VAR_aws_region }} || {
-            if aws s3api head-bucket --bucket ${{ env.S3_BUCKET_NAME }} 2>/dev/null; then
-            echo "Bucket already exists"
-            else
-            echo "Failed to create S3 bucket"
-            exit 1
-            fi}
+            echo "Creating S3 bucket and DynamoDB table for Terraform backend..."
     
-          # Create DynamoDB table
-          aws dynamodb create-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} \
-            --attribute-definitions AttributeName=LockID,AttributeType=S \
-            --key-schema AttributeName=LockID,KeyType=HASH \
-            --billing-mode PAY_PER_REQUEST \
-            --region ${{ env.TF_VAR_aws_region }} || {
-            ERROR_CODE=$?
-            if [ $ERROR_CODE -eq 400 ] && aws dynamodb describe-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} 2>/dev/null; then
-                echo "Table already exists"
-            else
-                echo "Failed to create DynamoDB table with error code $ERROR_CODE"
+            # Create S3 bucket
+            aws s3api create-bucket --bucket ${{ env.S3_BUCKET_NAME }} --region ${{ env.TF_VAR_aws_region }} || {
+            if aws s3api head-bucket --bucket ${{ env.S3_BUCKET_NAME }} 2>/dev/null; then
+                echo "Bucket already exists"
+              else
+                echo "Failed to create S3 bucket"
                 exit 1
-            fi}
-
-          echo "S3 bucket and DynamoDB table setup complete."
+              fi
+            }
+    
+            # Create DynamoDB table
+            aws dynamodb create-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} \
+              --attribute-definitions AttributeName=LockID,AttributeType=S \
+              --key-schema AttributeName=LockID,KeyType=HASH \
+              --billing-mode PAY_PER_REQUEST \
+            --region ${{ env.TF_VAR_aws_region }} || {
+                ERROR_CODE=$?
+            if [ $ERROR_CODE -eq 400 ] && aws dynamodb describe-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} 2>/dev/null; then
+                  echo "Table already exists"
+                else
+                  echo "Failed to create DynamoDB table with error code $ERROR_CODE"
+                  exit 1
+                fi
+              }
+    
+            echo "S3 bucket and DynamoDB table setup complete."
+        env:
+          TF_VAR_aws_region: eu-west-1
+          S3_BUCKET_NAME: terraform-backend
+          DYNAMODB_TABLE_NAME: terraform-locks
 
       - name: Setup .NET
         if: ${{ github.event.inputs.action == 'deploy' }}
