fix github pipeline errors

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,7 +22,7 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Setup AWS Credentials
         run: |
@@ -42,36 +42,64 @@ jobs:
       - name: Create S3 Bucket and DynamoDB Table for Terraform Backend
         run: |
           echo "Creating S3 bucket and DynamoDB table for Terraform backend..."
-          aws s3api create-bucket --bucket ${{ env.S3_BUCKET_NAME }} --region ${{ env.TF_VAR_aws_region }} || echo "Bucket already exists"
+
+          # Create S3 bucket
+          aws s3api create-bucket --bucket ${{ env.S3_BUCKET_NAME }} --region ${{ env.TF_VAR_aws_region }} || {
+            if aws s3api head-bucket --bucket ${{ env.S3_BUCKET_NAME }} 2>/dev/null; then
+            echo "Bucket already exists"
+            else
+            echo "Failed to create S3 bucket"
+            exit 1
+            fi}
+    
+          # Create DynamoDB table
           aws dynamodb create-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} \
             --attribute-definitions AttributeName=LockID,AttributeType=S \
             --key-schema AttributeName=LockID,KeyType=HASH \
             --billing-mode PAY_PER_REQUEST \
-            --region ${{ env.TF_VAR_aws_region }} || echo "Table already exists"
+            --region ${{ env.TF_VAR_aws_region }} || {
+            ERROR_CODE=$?
+            if [ $ERROR_CODE -eq 400 ] && aws dynamodb describe-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} 2>/dev/null; then
+                echo "Table already exists"
+            else
+                echo "Failed to create DynamoDB table with error code $ERROR_CODE"
+                exit 1
+            fi}
+
           echo "S3 bucket and DynamoDB table setup complete."
 
       - name: Setup .NET
         if: ${{ github.event.inputs.action == 'deploy' }}
-        uses: actions/setup-dotnet@v1
+        uses: actions/setup-dotnet@v4
         with:
           dotnet-version: '8.0.x'
 
       - name: Restore dependencies and build
         if: ${{ github.event.inputs.action == 'deploy' }}
         run: |
-          echo "Restoring dependencies and building the project..."
-          dotnet publish -c Release -o ./publish
-          echo "Project build complete."
+            echo "Restoring dependencies and building the project..."
+            dotnet publish AWSLambdaProject/AWSLambdaProject.csproj -c Release -o ./publish
+            if [ -d "./publish" ]; then
+                echo "Project build complete and output directory exists."
+            else
+                echo "Build failed or output directory not found."
+                exit 1
+            fi
         working-directory: .
 
       - name: Zip artifacts
         if: ${{ github.event.inputs.action == 'deploy' }}
         run: |
-          echo "Zipping artifacts..."
-          cd ./publish
-          zip -r lambda-deployment-package.zip .
-          echo "Artifacts zipped and ready for deployment."
-        working-directory: ./publish
+            echo "Zipping artifacts..."
+            if [ -d "./publish" ]; then
+              cd ./publish
+              zip -r lambda-deployment-package.zip .
+              echo "Artifacts zipped and ready for deployment."
+            else
+              echo "Publish directory not found."
+              exit 1
+            fi
+        working-directory: .
 
       - name: Deploy Lambda using Terraform
         if: ${{ github.event.inputs.action == 'deploy' }}
