separate creation of bucket and table for terraform backend in 2 steps

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,40 +32,61 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.TF_VAR_aws_region }}
-          
-      - name: Log selected action
-        run: echo "Selected action ${{ github.event.inputs.action }}"
 
-      - name: Create S3 Bucket and DynamoDB Table for Terraform Backend
+      - name: Check if S3 bucket exists
         run: |
-            echo "Creating S3 bucket and DynamoDB table for Terraform backend..."
-    
-            # Create S3 bucket
-            aws s3api create-bucket --bucket ${{ env.S3_BUCKET_NAME }} --region ${{ env.TF_VAR_aws_region }} --create-bucket-configuration LocationConstraint=${{ env.TF_VAR_aws_region }} || {
             if aws s3api head-bucket --bucket ${{ env.S3_BUCKET_NAME }} 2>/dev/null; then
+              echo "S3 bucket already exists."
+              echo "S3_BUCKET_EXISTS=true" >> $GITHUB_ENV
+            else
+              echo "S3 bucket does not exist."
+              echo "S3_BUCKET_EXISTS=false" >> $GITHUB_ENV
+            fi
+
+
+      - name: Create S3 Bucket if not exists
+        if: ${{ env.S3_BUCKET_EXISTS == 'false' }}
+        run: |
+            echo "Creating S3 bucket..."
+            aws s3api create-bucket --bucket ${{ env.S3_BUCKET_NAME }} --region ${{ env.TF_VAR_aws_region }} --create-bucket-configuration LocationConstraint=${{ env.TF_VAR_aws_region }} || {
+              if aws s3api head-bucket --bucket ${{ env.S3_BUCKET_NAME }} 2>/dev/null; then
                 echo "Bucket already exists"
               else
                 echo "Failed to create S3 bucket"
                 exit 1
               fi
             }
-    
-            # Create DynamoDB table
+            echo "S3 bucket created successfully."
+
+
+      - name: Check if DynamoDB table exists
+        run: |
+            if aws dynamodb describe-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} 2>/dev/null; then
+              echo "DynamoDB table already exists."
+              echo "DYNAMODB_TABLE_EXISTS=true" >> $GITHUB_ENV
+            else
+              echo "DynamoDB table does not exist."
+              echo "DYNAMODB_TABLE_EXISTS=false" >> $GITHUB_ENV
+            fi
+
+      - name: Create DynamoDB Table if not exists
+        if: ${{ env.DYNAMODB_TABLE_EXISTS == 'false' }}
+        run: |
+            echo "Creating DynamoDB table..."
             aws dynamodb create-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} \
               --attribute-definitions AttributeName=LockID,AttributeType=S \
               --key-schema AttributeName=LockID,KeyType=HASH \
               --billing-mode PAY_PER_REQUEST \
-            --region ${{ env.TF_VAR_aws_region }} || {
-                ERROR_CODE=$?
-            if [ $ERROR_CODE -eq 400 ] && aws dynamodb describe-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} 2>/dev/null; then
-                  echo "Table already exists"
-                else
-                  echo "Failed to create DynamoDB table with error code $ERROR_CODE"
-                  exit 1
-                fi
-              }
-    
-            echo "S3 bucket and DynamoDB table setup complete."
+              --region ${{ env.TF_VAR_aws_region }} || {
+              ERROR_CODE=$?
+              if [ $ERROR_CODE -eq 400 ] && aws dynamodb describe-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} 2>/dev/null; then
+                echo "Table already exists"
+              else
+                echo "Failed to create DynamoDB table with error code $ERROR_CODE"
+                exit 1
+              fi
+            }
+            echo "DynamoDB table created successfully."
 
       - name: Setup .NET
         if: ${{ github.event.inputs.action == 'deploy' }}
